// reportGenerator.ts
// PDF is generated by capturing actual chat content via html2canvas
// so the output is pixel-perfect identical to what is shown in the chat.

import { supabase } from './supabaseClient';

// ───────────────────────────────────────────────────────────
// HELPERS
// ───────────────────────────────────────────────────────────

const nowWIB = () =>
  new Date().toLocaleString('id-ID', {
    timeZone: 'Asia/Jakarta',
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  }) + ' WIB';

/** Capture every TIFA response in the current page as a single canvas image */
const captureChatResponses = async (): Promise<HTMLCanvasElement | null> => {
  const html2canvas = (await import('html2canvas')).default;

  // All TIFA message wrappers
  const nodes = Array.from(
    document.querySelectorAll<HTMLElement>('[data-tifa-response]')
  );
  if (nodes.length === 0) return null;

  // Calculate total height
  const totalHeight = nodes.reduce((sum, el) => sum + el.scrollHeight + 24, 0);
  const maxWidth = Math.max(...nodes.map(el => el.scrollWidth));

  // Create a hidden container that holds clones of all TIFA messages
  const container = document.createElement('div');
  container.style.cssText = `
    position: fixed; left: -9999px; top: 0;
    width: ${maxWidth}px;
    background: #ffffff;
    padding: 24px 20px 8px 20px;
    font-family: 'Inter', system-ui, sans-serif;
  `;

  // Add header
  const header = document.createElement('div');
  header.style.cssText = 'margin-bottom: 20px;';
  header.innerHTML = `
    <div style="font-size:22px;font-weight:700;color:#E4002B;letter-spacing:-0.5px">TelkomInfra</div>
    <div style="font-size:15px;font-weight:600;color:#1f2937;margin-top:4px">Laporan Percakapan TIFA</div>
    <div style="font-size:12px;color:#6b7280;margin-top:2px">Dicetak pada: ${nowWIB()}</div>
    <hr style="margin:12px 0;border:none;border-top:1.5px solid #f0f0f0;">
  `;
  container.appendChild(header);

  // Clone each TIFA message block
  nodes.forEach((el, idx) => {
    const wrapper = document.createElement('div');
    wrapper.style.cssText = `
      margin-bottom: 20px;
      padding: 16px 18px;
      background: #fafafa;
      border-radius: 12px;
      border: 1px solid #f0f0f0;
      page-break-inside: avoid;
    `;

    // Label
    const label = document.createElement('div');
    label.style.cssText = 'font-size:11px;font-weight:700;color:#E4002B;margin-bottom:10px;text-transform:uppercase;letter-spacing:0.5px';
    label.textContent = `TIFA — Respons ${idx + 1}`;
    wrapper.appendChild(label);

    const clone = el.cloneNode(true) as HTMLElement;
    // Remove timestamp & name header from clone (they're already in label)
    const headerEl = clone.querySelector('.flex.items-center.gap-2.mb-1\\.5');
    if (headerEl) headerEl.remove();

    clone.style.cssText = 'width:100%; overflow:visible;';
    wrapper.appendChild(clone);
    container.appendChild(wrapper);
  });

  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      allowTaint: true,
      backgroundColor: '#ffffff',
      logging: false,
      width: container.scrollWidth,
      height: container.scrollHeight,
      windowWidth: container.scrollWidth,
    });
    return canvas;
  } finally {
    document.body.removeChild(container);
  }
};

// ───────────────────────────────────────────────────────────
// PDF GENERATOR  —  main export
// ───────────────────────────────────────────────────────────

export const generatePDFReport = async (reportType: string, period: string): Promise<string> => {
  const { jsPDF } = await import('jspdf');

  // 1. Capture chat content
  const chatCanvas = await captureChatResponses();

  const pageW = 210; // A4 mm
  const pageH = 297;
  const margin = 14;
  const contentW = pageW - margin * 2;

  const doc = new jsPDF('portrait', 'mm', 'a4');

  // Cover page header
  doc.setFontSize(20);
  doc.setTextColor(220, 38, 38);
  doc.text('TelkomInfra', margin, 22);

  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text(reportType || 'Laporan Keuangan', margin, 31);

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Periode: ${period}   |   Dicetak: ${nowWIB()}`, margin, 38);

  // Red divider line
  doc.setDrawColor(220, 38, 38);
  doc.setLineWidth(0.5);
  doc.line(margin, 42, pageW - margin, 42);

  if (chatCanvas) {
    // Embed chat screenshot — split into A4 pages
    const imgData = chatCanvas.toDataURL('image/png');
    const imgW = contentW;
    const imgH = (chatCanvas.height / chatCanvas.width) * imgW;

    const startY = 48;
    const availH = pageH - startY - 10; // first page
    const fullPageH = pageH - margin * 2; // subsequent pages

    if (imgH <= availH) {
      // Fits in one page
      doc.addImage(imgData, 'PNG', margin, startY, imgW, imgH);
    } else {
      // Multi-page: slice the image vertically
      const scale = chatCanvas.width / imgW; // pixels per mm
      let yOffset = 0; // mm already consumed from the image

      // First page (smaller available area)
      const firstSliceH = availH;
      const firstSlicePx = firstSliceH * scale;

      const firstCanvas = document.createElement('canvas');
      firstCanvas.width = chatCanvas.width;
      firstCanvas.height = firstSlicePx;
      firstCanvas.getContext('2d')!.drawImage(
        chatCanvas, 0, 0, chatCanvas.width, firstSlicePx,
        0, 0, chatCanvas.width, firstSlicePx
      );
      doc.addImage(firstCanvas.toDataURL('image/png'), 'PNG', margin, startY, imgW, firstSliceH);
      yOffset += firstSliceH;

      // Remaining pages
      while (yOffset < imgH) {
        doc.addPage();
        const remainH = imgH - yOffset;
        const sliceH = Math.min(fullPageH, remainH);
        const slicePx = sliceH * scale;
        const startPx = yOffset * scale;

        const sliceCanvas = document.createElement('canvas');
        sliceCanvas.width = chatCanvas.width;
        sliceCanvas.height = slicePx;
        sliceCanvas.getContext('2d')!.drawImage(
          chatCanvas, 0, startPx, chatCanvas.width, slicePx,
          0, 0, chatCanvas.width, slicePx
        );
        doc.addImage(sliceCanvas.toDataURL('image/png'), 'PNG', margin, margin, imgW, sliceH);
        yOffset += sliceH;
      }
    }
  } else {
    // No chat content found — show a message
    doc.setFontSize(11);
    doc.setTextColor(100, 100, 100);
    doc.text(
      'Tidak ada konten percakapan TIFA yang ditemukan.\nMulai percakapan terlebih dahulu, lalu minta laporan.',
      margin, 55
    );
  }

  // Footer on every page
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(180, 180, 180);
    doc.text(
      `TelkomInfra | TIFA AI Financial Assistant   —   Halaman ${p} / ${totalPages}`,
      margin, pageH - 8
    );
  }

  const blob = doc.output('blob');
  return URL.createObjectURL(blob);
};

// ───────────────────────────────────────────────────────────
// EXCEL GENERATOR  (unchanged structure, kept for compat)
// ───────────────────────────────────────────────────────────

const getRealData = async (reportType: string, _period: string) => {
  if (reportType.toLowerCase().includes('po outstanding') || reportType.toLowerCase().includes('purchase order')) {
    const { data, error } = await supabase.from('purchase_orders').select('*').eq('status', 'Outstanding').limit(50);
    if (error || !data || data.length === 0) {
      return [['No', 'PO Number', 'Vendor', 'Date', 'Amount (Rp)', 'Status'], ['-', 'Tidak ada data', '-', '-', '-', '-']];
    }
    return [
      ['No', 'PO Number', 'Vendor', 'Date', 'Amount (Rp)', 'Status'],
      ...data.map((item: any, i: number) => [
        (i + 1).toString(), item.po_number || '-', item.vendor || '-',
        item.date || '-', (item.amount || 0).toLocaleString('id-ID'), item.status || '-'
      ])
    ];
  }
  if (reportType.toLowerCase().includes('cash flow') || reportType.toLowerCase().includes('cash_in')) {
    const { data, error } = await supabase.from('cash_in').select('*').limit(50);
    if (error || !data || data.length === 0) {
      return [['Date', 'Description', 'Category', 'Amount (Rp)'], ['-', 'Tidak ada data', '-', '-']];
    }
    return [
      ['Date', 'Description', 'Category', 'Amount (Rp)'],
      ...data.map((item: any) => [
        item.date || '-', item.description || '-', item.category || '-',
        (item.amount || 0).toLocaleString('id-ID')
      ])
    ];
  }
  return [['Informasi', 'Keterangan'], ['Status', 'Laporan ini tidak memiliki pemetaan spesifik ke database.']];
};

export const generateExcelReport = async (reportType: string, period: string): Promise<string> => {
  const XLSX = await import('xlsx');
  const data = await getRealData(reportType, period);

  const worksheet = XLSX.utils.aoa_to_sheet([
    [`TelkomInfra — ${reportType}`],
    [`Periode: ${period}`],
    [`Dicetak: ${nowWIB()}`],
    [],
    ...data,
  ]);

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');
  const buffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  return URL.createObjectURL(new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  }));
};

// ───────────────────────────────────────────────────────────
// WORD GENERATOR  (unchanged structure, kept for compat)
// ───────────────────────────────────────────────────────────

export const generateWordReport = async (reportType: string, period: string): Promise<string> => {
  const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, BorderStyle, WidthType } = await import('docx');
  const data = await getRealData(reportType, period);

  const tableRows = data.map((row, rowIndex) =>
    new TableRow({
      children: row.map(cellText =>
        new TableCell({
          children: [new Paragraph({ text: String(cellText) })],
          shading: rowIndex === 0 ? { fill: 'DC2626' } : undefined,
        })
      ),
    })
  );

  const wordDoc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({ children: [new TextRun({ text: 'TelkomInfra', bold: true, size: 36, color: 'DC2626' })] }),
        new Paragraph({ children: [new TextRun({ text: reportType, bold: true, size: 28 })], spacing: { before: 200, after: 200 } }),
        new Paragraph({ children: [new TextRun({ text: `Periode: ${period}   |   Dicetak: ${nowWIB()}`, size: 22, color: '666666' })], spacing: { after: 400 } }),
        new Table({ rows: tableRows, width: { size: 100, type: WidthType.PERCENTAGE }, borders: { top: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' }, bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' }, left: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' }, right: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' } } }),
      ],
    }],
  });

  const blob = await Packer.toBlob(wordDoc);
  return URL.createObjectURL(blob);
};
