import { NextRequest } from 'next/server';
import puppeteer from 'puppeteer';
import { launchTifaBrowser } from '@/lib/serverBrowser';

export const runtime = 'nodejs';
type Payload = { type?: 'bar' | 'line' | 'pie' | 'table'; title?: string; xAxisKey?: string; keys?: string[]; colors?: string[]; data?: Array<Record<string, unknown>>; headers?: string[]; rows?: Array<Array<unknown>> };
const colors: Record<string, string> = { red:'#dc2626', blue:'#2563eb', emerald:'#059669', green:'#16a34a', amber:'#d97706', orange:'#ea580c', purple:'#7c3aed', slate:'#475569' };
const esc = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c] || c));
const num = (v: unknown) => { const n = Number(String(v ?? '').replace(/[^0-9.-]/g, '')); return Number.isFinite(n) ? n : 0; };
const fmt = (v: unknown) => new Intl.NumberFormat('id-ID', { maximumFractionDigits: 2 }).format(num(v));

function table(p: Payload) { return `<table><thead><tr>${(p.headers || []).map((h) => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${(p.rows || []).map((r) => `<tr>${(p.headers || []).map((_, i) => `<td>${esc(r[i])}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
function bar(p: Payload) { const d=p.data||[]; const x=p.xAxisKey||'kategori'; const keys=p.keys?.length?p.keys:Object.keys(d[0]||{}).filter(k=>k!==x); const max=Math.max(...d.flatMap(r=>keys.map(k=>num(r[k]))),1); return `<div class="bars">${d.map(r=>`<div class="row"><b>${esc(r[x])}</b><div>${keys.map((k,i)=>{const v=num(r[k]);return `<div class="bar"><span style="width:${Math.max(2,v/max*100)}%;background:${colors[p.colors?.[i]||'blue']||p.colors?.[i]||'#2563eb'}"></span><em>${esc(fmt(v))}</em><small>${esc(k)}</small></div>`}).join('')}</div></div>`).join('')}</div>`; }
function line(p: Payload) { const d=p.data||[]; const x=p.xAxisKey||'kategori'; const k=p.keys?.[0]||Object.keys(d[0]||{}).find(a=>a!==x)||'nilai'; const vals=d.map(r=>num(r[k])); const max=Math.max(...vals,1), w=900,h=360,l=75,t=25,b=70,pw=w-l-25,ph=h-t-b; const point=(v:number,i:number)=>`${l+(d.length<2?pw/2:i*pw/(d.length-1))},${t+ph-v/max*ph}`; return `<svg viewBox="0 0 ${w} ${h}"><line x1="${l}" y1="${t+ph}" x2="${w-25}" y2="${t+ph}"/><polyline points="${vals.map(point).join(' ')}" fill="none" stroke="#2563eb" stroke-width="6"/>${vals.map((v,i)=>{const [px,py]=point(v,i).split(',');return `<circle cx="${px}" cy="${py}" r="8" fill="#2563eb"/><text x="${px}" y="${Number(py)-15}" text-anchor="middle">${esc(fmt(v))}</text><text x="${px}" y="${h-25}" text-anchor="middle">${esc(String(d[i][x]).slice(0,14))}</text>`}).join('')}</svg>`; }
function pie(p: Payload) { const d=p.data||[]; const x=p.xAxisKey||'kategori'; const k=p.keys?.[0]||Object.keys(d[0]||{}).find(a=>a!==x)||'nilai'; const total=Math.max(d.reduce((a,r)=>a+num(r[k]),0),1); let at=0; const slices=d.map((r,i)=>{const s=at/total*360;at+=num(r[k]);const c=colors[p.colors?.[i]||['blue','emerald','amber','red','purple'][i%5]]||'#2563eb';return {r,i,s,e:at/total*360,c}}); return `<div class="pie"><div class="donut" style="background:conic-gradient(${slices.map(a=>`${a.c} ${a.s}deg ${a.e}deg`).join(',')})"></div><div>${slices.map(a=>`<p><i style="background:${a.c}"></i>${esc(a.r[x])}: ${esc(fmt(a.r[k]))} (${(num(a.r[k])/total*100).toFixed(1)}%)</p>`).join('')}</div></div>`; }
function body(p: Payload) { return p.type==='table'?table(p):p.type==='line'?line(p):p.type==='pie'?pie(p):bar(p); }

export async function POST(req: NextRequest) { const expected=process.env.WHATSAPP_INTERNAL_TOKEN; if(!expected||req.headers.get('authorization')!==`Bearer ${expected}`) return new Response('Unauthorized',{status:401}); let browser: puppeteer.Browser|undefined; try { const p=await req.json() as Payload; if(!p.title||!['bar','line','pie','table'].includes(p.type||'')) return new Response('Invalid visual payload',{status:400}); const html=`<!doctype html><meta charset="utf-8"><style>body{margin:0;background:#fff;color:#172033;font-family:Arial,"Noto Sans",sans-serif}.card{width:1000px;padding:38px 44px}.title{font-size:30px;font-weight:bold;margin-bottom:26px}svg{width:100%;height:auto}svg line{stroke:#cbd5e1;stroke-width:2}svg text{fill:#475569;font-size:16px}.bars{display:flex;flex-direction:column;gap:22px}.row{display:grid;grid-template-columns:270px 1fr;gap:18px;font-size:18px}.bar{height:28px;background:#eef2f7;border-radius:8px;margin-bottom:13px;position:relative}.bar span{display:block;height:100%;border-radius:8px}.bar em{position:absolute;right:8px;top:4px;color:#fff;font-style:normal;font-size:14px;font-weight:bold;text-shadow:0 1px 2px #334155}.bar small{position:absolute;left:0;top:32px;color:#64748b;font-size:12px}table{width:100%;border-collapse:collapse;font-size:16px}th{background:#172033;color:#fff;text-align:left;padding:13px 10px}td{padding:12px 10px;border:1px solid #e2e8f0}tr:nth-child(even){background:#f8fafc}.pie{display:flex;align-items:center;gap:50px}.donut{width:360px;height:360px;border-radius:50%}.pie p{font-size:18px}.pie i{display:inline-block;width:15px;height:15px;border-radius:4px;margin-right:10px}</style><main class="card"><div class="title">${esc(p.title)}</div>${body(p)}</main>`; browser=await launchTifaBrowser(); const page=await browser.newPage(); await page.setViewport({width:1000,height:800,deviceScaleFactor:2}); await page.setContent(html,{waitUntil:'networkidle0'}); const png=await page.screenshot({type:'png',fullPage:true}); return new Response(png,{headers:{'Content-Type':'image/png'}}); } catch(e:any) { console.error('[WhatsApp visual]',e); return new Response(e.message||'Visual generation failed',{status:500}); } finally { await browser?.close(); } }